subject = "subject1/" #Name subject
media_folder = "gestures/" # Where to store gesture images
gestures = [2, 3, 4] # What gestures to include

[sgt_args]
num_reps = 1 # Number of repetitions for each gesture
rep_time = 5 # Time of each repetition
rest_time = 3 # Rest time between repetitions

# Booleans must be lowercase
auto_advance = true # Advance to next repetition automatically
discrete = false # Press and hold space bar during repetition instead of timed repetition

[streamer]
name = "SifiBand_2F4C" # Name of SiFi band to connect to
ecg = true # Collect ECG data
emg = true # Collect EMG data
eda = true # Collect EDA data
imu = true # Collect IMU data
ppg = true # Collect PPG data
temperature = true # Collect temperature data

filtering = false # Activate/deactivate filtering
emg_notch_freq = 60 # Frequency for EMG notch filter
emg_bandpass = [20, 450] # Upper and lower cutoff frequency for EMG band pass filter
eda_bandpass = [0, 5] # Upper and lower cutoff frequency for EDA band pass filter
eda_freq = 0 # EDA excitation frequency

streaming = true # Low latency mode (only supported for BioPoint v1.3 and up)
night_mode = false # Turn off LEDs during data acquisition
high_gain = false # # Use more of the ECG/EMG ADC's dynamic range, at the cost of saturating more easily

ecg_fs = 500 # set ECG sampling rate
emg_fs = 2000 # set EMG sampling rate
eda_fs = 50 # set EDA sampling rate
imu_fs = 50 # set IMU sampling rate
ppg_sps = 50 # set PPG sampling rate
ppg_avg = 1 # set PPG averaging factor
temperature_fs = 1 # set ECG sampling rate
